FROM maven:3.6.0-jdk-8
ADD . .
RUN mvn -version
RUN mvn clean
ENTRYPOINT ["./src/main/java/com/coda/terminal/javapract2"]
RUN ["chmod", "+x", "./src/main/java/com/coda/terminal/javapract2"]
CMD ["mvn", "exec:java","-Dexec.mainClass=com.coda.terminal.javapract2"]
